name: google_books
description: Books App with Flutter using google books api.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  http: ^0.13.4
  url_launcher: ^6.0.17
  provider: ^6.0.2
  sqflite: ^2.0.1
  shared_preferences: ^2.0.11
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/book_icon.png"






  flutter_lints: ^1.0.0


flutter:




  uses-material-design: true































