name: google_books
description: Books App with Flutter using google books api.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.2.6
  provider: ^6.1.2
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/book_icon.png"

flutter:

  uses-material-design: true